#!/usr/bin/env ruby
require File.expand_path(File.dirname(__FILE__) + '/../config/boot')
require 'net/smtp'

invalid_ipns = SMQueue(:name => "/queue/ipn.invalid",
                       :host => "mq.your-domain.com", :adapter => :StompAdapter)

invalid_ipns.get do |message|
  ipn = Ipn.from_xml(message.body)
  msg = <<-EMAIL
From: Payment Processing <from@your-domain.com>
To: Accounts <notifications@your-domain.com>
Subject: Invalid IPN

The following IPN was received but found to be invalid.

#{ipn.to_xml}

--
This email was sent automatically by the invalid IPN notifier.
EMAIL

  Net::SMTP.start('localhost') do |smtp|
    smtp.send_message msg, "from@your-domain.com", "notifications@your-domain.com"
  end
end